// Slime — three physarum species locked in a cycle none of them can win.
//
// Millions of agents each do something trivial: sense the trail ahead of them
// in three directions, steer towards the strongest, step forward, and deposit.
// A separate pass blurs and decays the trail. That feedback loop — deposit,
// diffuse, follow — is the whole model, and it self-organises into transport
// networks that no part of the code describes.
//
// After Jeff Jones, "Characteristics of pattern formation and evolution in
// approximations of Physarum transport networks" (2010).
//
// # Why this is not the textbook model
//
// The textbook model *converges*. Every agent is attracted to the same field it
// deposits into, so the whole system is descending a single landscape, and once
// it reaches the bottom the picture stops being worth looking at. The Kura
// visual next door never does that, and the mechanisms below are why — each one
// transcribed here into physarum's terms.
//
// ## 1. A cycle, not a chase
//
// Kura runs three flocks that pull on each other by unequal amounts (heavy
// pulls light at 1.8, light pulls back at 0.8). An interaction that is not
// symmetric has no energy function to minimise, so there is no bottom to
// descend to.
//
// Two species gave that, but only as a pursuit: A chased B, B ran, and the
// front where they met wandered off and dissipated. Nothing brought it back,
// and the frame stayed a uniform carpet at a single scale.
//
// Three species in a *cycle* close it. A is drawn to B's trail, B to C's, C to
// A's, and each is pushed off the trail of whichever one hunts it. No species
// can win, and — this is the part that matters — a point where all three meet
// cannot resolve itself into any of the three. It is a topological defect, it
// is pinned, and the fronts wind around it. What that produces is spiral waves
// tens of times the width of a filament, nucleating, drifting, colliding and
// annihilating in pairs. That is the scale the visual was missing: large form,
// generated by nothing but three local rules.
//
// ## 2. Noise proportional to local order
//
// Kura kicks the boids that already agree with their neighbours hardest, so
// alignment is punished exactly where it appears. Here an agent sitting in a
// wide settled groove — every sensor reading strong, nothing to choose between
// them — gets turned at random; an agent out in open territory is left alone.
//
// ## 3. A crowd does not couple
//
// Kura's oscillators only pull on each other in pairs or trios and ignore a
// crowd entirely, which is what stops the whole screen synchronising. Here a
// texel reinforced past saturation stops attracting altogether, so an artery
// that thickens too far pushes agents onto its own walls and splits.
//
// ## 4. Agents inherit what works
//
// Every agent carries a heritable trait setting how wide it senses and how fast
// it runs, and continuously drifts that trait towards whatever is working in
// the patch of frame it is standing in. Successful shapes therefore *spread*,
// and the frame develops regions that are morphologically different organisms —
// fine lace in one place, broad arteries in another — with boundaries that move
// as one is invaded by the next. See `crowd_veto` for why this does not simply
// coarsen into one winner.

#import fete::noise::{hash11, hash12}

struct Agent {
    pos: vec2<f32>,
    angle: f32,
    // Two things in one float, which is what keeps the agent four floats wide —
    // worth caring about at two million of them.
    //
    // The **integer part** is the species, 0, 1 or 2, and is fixed for the
    // agent's life. The **fractional part** is the heritable trait, and drifts
    // every frame. `species_of` and `gene_of` are the only things that should
    // take this apart.
    kind: f32,
}

struct SlimeParams {
    resolution: vec2<f32>,
    agent_count: u32,
    time: f32,
    delta: f32,
    sensor_angle: f32,
    sensor_distance: f32,
    turn_speed: f32,
    move_speed: f32,
    deposit: f32,
    decay: f32,
    diffuse: f32,
    // Radial shove on the downbeat. Signed: positive pushes away from the
    // centre, negative pulls towards it, and the two alternate.
    impulse: f32,
}

// Rgba16Float. `.r`, `.g` and `.b` carry the three species' trails and are
// never summed here, only in the display pass — the whole point is that an
// agent can tell them apart. `.a` carries the trait field: the locally
// successful gene, which is how a trait spreads from one agent to the next.
@group(0) @binding(0) var trail_read: texture_storage_2d<rgba16float, read>;
@group(0) @binding(1) var trail_write: texture_storage_2d<rgba16float, write>;
@group(0) @binding(2) var<storage, read_write> agents: array<Agent>;
// Deposits accumulate here as fixed point rather than straight into the trail
// texture. Many agents land on the same texel in the same dispatch, and only
// an atomic add gets that right — a read-modify-write on a storage texture
// would silently drop most of them.
//
// Five slots per texel: one trail per species, then the two running totals the
// trait field needs — sum of `gene * success` and sum of `success` — because a
// weighted mean cannot be accumulated in one number.
@group(0) @binding(3) var<storage, read_write> deposits: array<atomic<u32>>;
@group(0) @binding(4) var<uniform> params: SlimeParams;

const SPECIES_COUNT: u32 = 3u;
const SLOTS_PER_TEXEL: u32 = 5u;
const SLOT_GENE: u32 = 3u;
const SLOT_WEIGHT: u32 = 4u;

// Deposits are scaled to fixed point before the atomic add. 1024 leaves plenty
// of headroom below u32 overflow while resolving contributions well under one
// unit of trail.
const DEPOSIT_SCALE: f32 = 1024.0;
const PI: f32 = 3.141592653589793;
const TAU: f32 = 6.283185307179586;

// ------------------------------------------------------------ species coupling

/// How strongly an agent follows the trail its own species laid.
const SELF_AFFINITY: f32 = 1.0;
/// How strongly an agent is drawn to the trail of the species it hunts, and
/// pushed off the trail of the species that hunts it — at the two ends of the
/// heritable gene. A timid agent barely chases and runs hard; a bold one
/// chases hard and stands its ground.
///
/// **Chasing stays smaller than fleeing at both ends, and that ordering is
/// load-bearing rather than a taste.** If chasing outweighs fleeing, then a
/// texel holding all three species is *more* attractive to each of them than a
/// texel holding only its own — so they pile onto the same filaments and the
/// cycle never separates into anything. The first version had these the other
/// way round and produced exactly that: one network with faint colour
/// fringing, and no territory at all.
///
/// Boldness rides on the gene so that a trait domain is not merely a patch of
/// different-looking network but a patch that plays the cycle differently —
/// timid regions give ground and bold ones press into their prey, which is
/// what couples the trait field to the territories rather than leaving the two
/// as unrelated layers over the same frame.
///
/// It was originally put here for a different and wrong reason: to stop the
/// trait converging, on the theory that boldness has no single best value. It
/// does not stop it. Neutralising the rest of the gene and leaving only
/// boldness heritable converged just the same, which is what eventually ruled
/// out the entire family of explanations involving selection.
const CHASE_TIMID: f32 = 0.30;
const CHASE_BOLD: f32 = 0.85;
const FLEE_TIMID: f32 = -1.35;
const FLEE_BOLD: f32 = -0.95;
/// How strongly a species is pushed off the trail of the one that hunts it.
///
/// Negative, where Kura's corresponding weight is merely small. Kura gets its
/// repulsion from a separation force that physarum has no equivalent of — an
/// agent here has no notion of another agent at all, only of trail — so the
/// cross-coupling has to carry the pushing-apart itself. The magnitudes stay
/// unequal for the same reason Kura's are: a chase only stays a chase while one
/// side wants it more than the other side minds.
///
/// They are also unequal for a second reason now. If `CHASE` and `-FLEE` were
/// the same size the cycle would be balanced, and a balanced cycle drifts
/// towards the neutral fixed point where all three species are evenly mixed
/// everywhere — which is a grey mush, not a spiral. The asymmetry is what
/// keeps the orbit away from the centre.

/// Per-species trail persistence, as an exponent on the nominal decay.
///
/// Kura's flocks are not interchangeable — the heavy discs are slow and carry
/// the structure, the shoal is quick and reacts to it — and three identical
/// species would waste the cycle on three copies of one organism. Species 0's
/// trail is the durable one and species 2's the most fleeting, so the three
/// arms of a spiral do not read as rotations of the same thing.
const DECAY_EXP: vec3<f32> = vec3<f32>(1.0, 1.18, 1.4);

/// How much further out a species reads the other two than it reads itself.
///
/// This is the knob that decides how big the pattern is. See [`appeal`].
const CYCLE_REACH: f32 = 5.0;

// ------------------------------------------------------------------ the gene
//
// The heritable trait, `0..1`. It sets three things at once: how wide an agent
// senses, how fast it moves, and how boldly it plays the cycle. The first two
// decide whether a region builds fine lace or broad arteries, which is what
// makes a domain visible; the third is what stops the whole thing converging on
// one answer. See `CHASE_TIMID`.
//
// The ranges are deliberately wider than the fixed per-agent jitter they
// replace: the point is for neighbouring regions to be visibly different
// organisms, not merely varied.

const GENE_ANGLE_LO: f32 = 0.60;
const GENE_ANGLE_HI: f32 = 1.50;
const GENE_SPEED_LO: f32 = 0.75;
const GENE_SPEED_HI: f32 = 1.30;

/// How fast an agent adopts the gene that is working around it, per second.
///
/// These two set the whole balance, and both had to move a long way from their
/// first guesses. What an agent copies is not another agent, it is the *field*
/// — a mean over the hundreds of agents that crossed that texel — and
/// averaging has already taken most of the variation out of it before anybody
/// reads it. So copying wins far more easily than the arithmetic for a single
/// pair would suggest, and it has to be set slow and the mutation fast to keep
/// a population that is still exploring after a few minutes.
///
/// Measured at 200 simulated seconds, from a mean of 0.105 and a spread of
/// 0.021 with the first values — a population squashed against the bottom of
/// its range — to a mean of 0.413 and a spread of 0.087, which uses 0.09 to
/// 0.89 of the range and is still moving.
const GENE_COPY_RATE: f32 = 0.4;
/// Random walk on the gene, per root-second. Without it a domain can never be
/// invaded by anything it has not already seen.
const GENE_MUTATION: f32 = 1.0;
/// How fast the trait field follows what agents report, per frame.
const GENE_BLEND: f32 = 0.08;
/// How much the trait field spreads sideways each frame. This is what lets a
/// domain grow into its neighbour rather than only hold what it has.
///
/// Small, because it compounds. At a quarter per frame the field was fully
/// mixed within a second or so and every domain's "local consensus" was the
/// global mean — the trait field had structure, but only a few percent of
/// contrast across the whole frame, which is no domains at all. A few percent
/// per frame is already a strong blur once it has run for a hundred of them.
const GENE_DIFFUSE: f32 = 0.03;
/// A gene of exactly 1.0 would carry into the integer part of `kind` and change
/// the agent's species. The field is half-open for that reason.
const GENE_MAX: f32 = 0.9995;

// -------------------------------------------------------------- crowd and order

/// Density at which a texel starts to stop attracting, and where it has
/// stopped entirely. Both sit above the trail's equilibrium inside a healthy
/// tube (~2.0, set by the deposit calibration on the Rust side), so ordinary
/// structure is untouched and only over-reinforced arteries are vetoed.
const SATURATED_LO: f32 = 2.4;
const SATURATED_HI: f32 = 6.0;

/// Turn applied at full local order, as a fraction of one ordinary turn step.
const ORDER_NOISE: f32 = 0.9;
/// Trail strength at which a groove counts as settled rather than merely found.
const SETTLED_LO: f32 = 0.8;
const SETTLED_HI: f32 = 2.4;

fn texel_index(coord: vec2<i32>) -> u32 {
    return u32(coord.y) * u32(params.resolution.x) + u32(coord.x);
}

fn deposit_index(coord: vec2<i32>, slot: u32) -> u32 {
    return texel_index(coord) * SLOTS_PER_TEXEL + slot;
}

fn in_bounds(coord: vec2<i32>) -> bool {
    return coord.x >= 0 && coord.y >= 0
        && coord.x < i32(params.resolution.x)
        && coord.y < i32(params.resolution.y);
}

fn wrapped(coord: vec2<i32>) -> vec2<i32> {
    let bounds = vec2<i32>(params.resolution);
    return (coord % bounds + bounds) % bounds;
}

/// A random step with a mean of exactly zero, in `-1..1`.
///
/// `hash11` is not centred. Over the argument patterns this shader feeds it,
/// its mean is 0.4956 rather than 0.5 — a bias of about -0.0044. That is
/// invisible in a one-shot decision such as breaking a tie between two
/// sensors, but anything that *integrates* it accumulates a drift, and two
/// things here do.
///
/// The gene random-walks every frame, and at this bias it loses 0.53 of its
/// range over 200 simulated seconds — more than half of it. That, and not the
/// fitness function, is why the trait field used to converge on its floor:
/// four separate attempts at making selection frequency-dependent all landed
/// on the same mean of 0.02 and the same spread of 0.014, which is the sort of
/// coincidence that means the thing being adjusted is not the cause. The turn
/// noise integrates it too, as a slight preferred direction of rotation given
/// to every agent in the frame — a global chirality nothing asked for.
///
/// The difference of two independent samples has mean exactly zero whatever
/// the marginal distribution's bias is, which fixes both for two hashes
/// instead of one.
fn centred(a: f32, b: f32) -> f32 {
    return hash11(a) - hash11(b);
}

fn species_of(kind: f32) -> u32 {
    return min(u32(floor(kind)), SPECIES_COUNT - 1u);
}

fn gene_of(kind: f32) -> f32 {
    return fract(kind);
}

/// All three species' trail strength ahead of an agent, at a given angular
/// offset.
///
/// Sensing must wrap exactly as movement and diffusion do. Treating off-screen
/// as unattractive instead makes every agent near a border turn away from it,
/// and they accumulate into a bright rim around the whole frame — a border
/// artefact with no counterpart in the model.
fn sense(pos: vec2<f32>, angle: f32, offset: f32, reach: f32) -> vec3<f32> {
    let dir = vec2<f32>(cos(angle + offset), sin(angle + offset));
    let sample_pos = pos + dir * params.sensor_distance * reach;
    return textureLoad(trail_read, wrapped(vec2<i32>(floor(sample_pos)))).rgb;
}

/// How attractive a patch of one's own trail is, given how much of it there is.
///
/// Rises with density up to the point where the tube is doing its job, then
/// falls back to nothing. This is Kura's "a crowd does not couple at all",
/// written for a field instead of for neighbours: past saturation an agent
/// stops being pulled into the middle of the artery and drifts to its walls,
/// which is what makes a thickening tube split rather than keep thickening.
///
/// It is also what stops the heritable trait coarsening into a single winner.
/// Selection on its own converges — the best gene spreads until it is the only
/// one left, which is exactly the settled state all of this exists to avoid.
/// Because an agent's contribution to the trait field is weighted by this
/// function rather than by raw trail, a gene that is doing *too* well stops
/// being copied. Success is rewarded; runaway success is not.
fn crowd_veto(density: f32) -> f32 {
    return density * (1.0 - smoothstep(SATURATED_LO, SATURATED_HI, density));
}

/// The signed value an agent steers by at one sensor.
///
/// Own trail read close in, plus the trail of the species it hunts and minus
/// the trail of the species that hunts it, both read much further out. Indices
/// run round the cycle: prey is the next species along, predator the one after.
///
/// The two ranges are the whole reason this produces anything larger than a
/// filament. When the cycle was read at the same distance as an agent's own
/// trail, the three species separated — but only onto adjacent tubes, because
/// a few texels was the only length they knew about. The pattern a cyclic
/// system makes is set by the range over which the species can feel each
/// other, so reading the other two from [`CYCLE_REACH`] times further away
/// puts the territories, and the spirals that wind between them, at that
/// scale instead. The fine network is still built at the short range, so the
/// filaments do not coarsen with the domains.
fn appeal(near: vec3<f32>, far: vec3<f32>, species: u32, gene: f32) -> f32 {
    let prey = far[(species + 1u) % SPECIES_COUNT];
    let predator = far[(species + 2u) % SPECIES_COUNT];
    let chase = mix(CHASE_TIMID, CHASE_BOLD, gene);
    let flee = mix(FLEE_TIMID, FLEE_BOLD, gene);
    return crowd_veto(near[species]) * SELF_AFFINITY + prey * chase + predator * flee;
}

@compute @workgroup_size(64)
fn update_agents(
    @builtin(global_invocation_id) gid: vec3<u32>,
    @builtin(num_workgroups) num_workgroups: vec3<u32>,
) {
    // The workload is folded across x and y because a few million agents
    // exceeds the 65535 workgroups-per-dimension limit.
    let index = gid.x + gid.y * num_workgroups.x * 64u;
    if index >= params.agent_count {
        return;
    }

    var agent = agents[index];
    let id = f32(index);
    let rng = centred(id * 0.017 + params.time * 13.7, id * 0.019 + params.time * 11.3 + 3.0);
    let rng_order = centred(id * 0.031 + params.time * 7.3 + 11.0, id * 0.037 + params.time * 9.7 + 17.0);
    let rng_gene = centred(id * 0.043 + params.time * 5.1 + 23.0, id * 0.047 + params.time * 6.7 + 29.0);

    let species = species_of(agent.kind);
    var gene = gene_of(agent.kind);

    let angle_bias = mix(GENE_ANGLE_LO, GENE_ANGLE_HI, gene);

    // Steering. Three sensors, and the agent turns towards whichever reads
    // strongest. Turning by a fixed amount rather than proportionally to the
    // difference is what keeps the networks crisp: proportional steering
    // averages the sensors out and the structure dissolves into fog.
    let raw_ahead = sense(agent.pos, agent.angle, 0.0, 1.0);
    let raw_left = sense(agent.pos, agent.angle, params.sensor_angle * angle_bias, 1.0);
    let raw_right = sense(agent.pos, agent.angle, -params.sensor_angle * angle_bias, 1.0);

    let far_ahead = sense(agent.pos, agent.angle, 0.0, CYCLE_REACH);
    let far_left = sense(agent.pos, agent.angle, params.sensor_angle * angle_bias, CYCLE_REACH);
    let far_right = sense(agent.pos, agent.angle, -params.sensor_angle * angle_bias, CYCLE_REACH);

    let ahead = appeal(raw_ahead, far_ahead, species, gene);
    let left = appeal(raw_left, far_left, species, gene);
    let right = appeal(raw_right, far_right, species, gene);

    let turn = params.turn_speed * params.delta * angle_bias;
    if ahead > left && ahead > right {
        // Already heading the right way; hold.
    } else if left > right {
        agent.angle += turn;
    } else if right > left {
        agent.angle -= turn;
    } else {
        // Sensors tied — usually virgin territory. A random turn here is what
        // seeds new branches instead of letting agents march in straight lines.
        agent.angle += rng * turn;
    }

    // Noise proportional to local order.
    //
    // Kura measures order as how closely a boid already agrees with its
    // neighbours and kicks the ones that agree most, so a flock can never
    // freeze into a crystal. The equivalent here is an agent deep inside an
    // established groove: all three sensors reading strong, and no meaningful
    // difference between them to steer by. Such an agent is following a
    // decision the network made some time ago rather than making one, and
    // turning it at random is what keeps tubes fraying and re-forming instead
    // of hardening in place. An agent out in open territory reads near zero
    // here and is left completely alone.
    let own = vec3<f32>(raw_ahead[species], raw_left[species], raw_right[species]);
    let strongest = max(own.x, max(own.y, own.z));
    let weakest = min(own.x, min(own.y, own.z));
    let uniformity = smoothstep(0.6, 1.0, weakest / (strongest + 1e-5));
    let order = uniformity * smoothstep(SETTLED_LO, SETTLED_HI, weakest);
    agent.angle += rng_order * turn * ORDER_NOISE * order;

    // Beat impulse: a radial shove from the centre, alternating direction from
    // bar to bar. The networks rebuild over the following second, so a kick
    // reads as the whole structure breathing.
    //
    // Three details, each of which was wrong in an earlier version and each of
    // which showed up as the middle of the frame going empty:
    //
    // * **The sign alternates.** A kick that always points outward is a
    //   permanent source at the centre. The field wraps, so everything it
    //   evicts re-enters at the borders and never finds its way back, and the
    //   middle thins out a little more on every bar until it is bare. Out on
    //   one bar and in on the next has zero net displacement over a pair, so
    //   the breath is a breath rather than a slow leak. The direction arrives
    //   as the *sign* of `impulse`; its magnitude is the strength.
    // * **The turn takes the short way round.** `agent.angle` accumulates
    //   without bound while `atan2` returns `-PI..PI`, so interpolating one
    //   towards the other swung an agent through whatever multiple of a turn
    //   happened to separate them. That is not a shove, it is a scramble whose
    //   violence grows with how long the agent has been alive, and it churned
    //   the middle of the frame — where the outward direction changes fastest
    //   — hardest of all.
    // * **A small exempt disc at the very centre.** The radial direction is
    //   undefined at the centre and ill-conditioned just around it, so the
    //   innermost few percent are left alone. Kept *small* on purpose: an
    //   exempt zone drains itself, because agents just outside it are pushed
    //   away on the outward bar while those inside are not pushed back in.
    //   Measured over 200 simulated seconds, exempting the innermost eighth
    //   left the middle at 0.80 of the surrounding brightness where an
    //   unkicked simulation sits at 1.12; a twentieth leaves it at 0.94.
    let strength = abs(params.impulse);
    if strength > 0.001 {
        let centre = params.resolution * 0.5;
        let from_centre = agent.pos - centre + vec2<f32>(0.001);
        let reach = smoothstep(0.0, 0.05, length(from_centre) / length(centre));
        // Not `target`: that is a reserved word in WGSL.
        let outward_angle = atan2(from_centre.y, from_centre.x);
        let aim = select(outward_angle + PI, outward_angle, params.impulse > 0.0);
        // Shortest signed arc from the current heading to the one we want.
        let delta = atan2(sin(aim - agent.angle), cos(aim - agent.angle));
        // Gentler than it was. With the cycle supplying its own large-scale
        // structure, a hard radial re-aim every bar competes with it — and
        // wins, pinning a spiral core at the middle of the frame, which reads
        // as scripted rather than emergent. At half the old strength the beat
        // is still felt as the whole field breathing and the pattern is left
        // to organise itself.
        agent.angle += delta * strength * reach * 0.18;
    }

    // Kept bounded. It is only ever read through `sin`/`cos` and the arc above,
    // all of which are indifferent to a whole turn, and a heading that grows
    // without limit loses precision over the length of a set.
    agent.angle = agent.angle % TAU;

    let speed = params.move_speed * mix(GENE_SPEED_LO, GENE_SPEED_HI, gene);
    var next = agent.pos + vec2<f32>(cos(agent.angle), sin(agent.angle)) * speed * params.delta;

    // Wrap at the edges. Reflecting instead would build up a visible rim of
    // agents along each border; wrapping keeps the density uniform and makes
    // the field read as a window onto something larger.
    next = (next + params.resolution) % params.resolution;
    agent.pos = next;

    // --- inheritance ---------------------------------------------------------
    //
    // Drift towards whatever gene is working here, and mutate. The trait field
    // is a success-weighted mean of what agents standing on this texel reported
    // last frame, so this is copying from the locally successful rather than
    // from the locally numerous — the difference between selection and a
    // popularity contest.
    let coord = vec2<i32>(floor(next));
    let here = textureLoad(trail_read, wrapped(coord));
    gene += (here.a - gene) * GENE_COPY_RATE * params.delta;
    // Scaled as a Wiener increment — the square root of the timestep, not the
    // timestep — because this is a random walk and not a drift. Kura's
    // oscillators take their phase noise the same way and for the same reason.
    //
    // Getting it wrong made the mutation about eight times weaker than
    // intended at 60fps, and weak enough that it lost to the copying: the
    // stationary spread of an Ornstein-Uhlenbeck process is the noise divided
    // by the square root of twice the pull rate, which worked out at 0.009
    // against a measured 0.015. That is the whole reason the trait field
    // converged, and it is worth writing down how long it took to find,
    // because the symptom pointed everywhere else first. Four attempts at
    // making selection frequency-dependent changed nothing, and neither did
    // fixing a genuine bias in the hash — the arithmetic that identified it in
    // the end was noticing that the spread the simulation settled at was
    // exactly the spread the mutation rate could support.
    gene += rng_gene * GENE_MUTATION * sqrt(params.delta);
    gene = clamp(gene, 0.0, GENE_MAX);

    agent.kind = f32(species) + gene;
    agents[index] = agent;

    if in_bounds(coord) {
        atomicAdd(&deposits[deposit_index(coord, species)], u32(params.deposit * DEPOSIT_SCALE));

        // How well this agent is doing, for the purpose of being copied. Its
        // own trail strength ahead of it, run through the same crowd veto that
        // governs attraction — so a gene doing well is copied and a gene doing
        // so well that it has saturated its own tube is not.
        //
        // Plain, and deliberately so. Three more elaborate schemes were tried
        // here first — sharpening the weight so the best few agents dominate,
        // paying a bonus for being rare, and making fitness depend on whether
        // an agent was standing in its prey's territory or its predator's —
        // and every one of them was an attempt to stop the trait field
        // converging. None of them worked, because the convergence was the
        // mutation being mis-scaled rather than anything about selection. With
        // that fixed, removing all three measured *better* than keeping them:
        // a spread of 0.094 against 0.087, over a mean nearer the middle of
        // the range. They are gone.
        let success = crowd_veto(raw_ahead[species]);
        atomicAdd(&deposits[deposit_index(coord, SLOT_GENE)], u32(gene * success * DEPOSIT_SCALE));
        atomicAdd(&deposits[deposit_index(coord, SLOT_WEIGHT)], u32(success * DEPOSIT_SCALE));
    }
}

@compute @workgroup_size(8, 8)
fn diffuse(@builtin(global_invocation_id) gid: vec3<u32>) {
    let coord = vec2<i32>(gid.xy);
    if !in_bounds(coord) {
        return;
    }

    // 3x3 box blur of the previous frame. Cheap, and one blur per frame
    // compounded over many frames approximates a gaussian anyway. All four
    // channels blur together: diffusion is a property of the medium, and the
    // trait field spreading sideways is how a domain grows into its neighbour.
    var sum = vec4<f32>(0.0);
    for (var dy = -1; dy <= 1; dy++) {
        for (var dx = -1; dx <= 1; dx++) {
            sum += textureLoad(trail_read, wrapped(coord + vec2<i32>(dx, dy)));
        }
    }
    let blurred = sum / 9.0;
    let original = textureLoad(trail_read, coord);

    var value = mix(original.rgb, blurred.rgb, params.diffuse);

    // Fold in this frame's deposits and clear the accumulators for the next.
    let deposited = vec3<f32>(
        f32(atomicExchange(&deposits[deposit_index(coord, 0u)], 0u)),
        f32(atomicExchange(&deposits[deposit_index(coord, 1u)], 0u)),
        f32(atomicExchange(&deposits[deposit_index(coord, 2u)], 0u)),
    ) / DEPOSIT_SCALE;
    value += deposited;

    // Decay. Without it the trail saturates everywhere within seconds and the
    // agents lose the gradient they are following. Each species decays at its
    // own rate, so the three arms of a spiral persist for different lengths of
    // time and the wave has a front and a wake rather than being symmetric.
    value *= pow(vec3<f32>(params.decay), DECAY_EXP);

    // The trait field. Spread sideways, then pulled towards the success-
    // weighted mean gene the agents standing here reported. Where nobody
    // reported anything — open territory, no trail — it keeps what it had, so
    // a domain's memory of itself survives the network moving off it and back.
    var gene_field = mix(original.a, blurred.a, GENE_DIFFUSE);
    let gene_sum = f32(atomicExchange(&deposits[deposit_index(coord, SLOT_GENE)], 0u));
    let weight = f32(atomicExchange(&deposits[deposit_index(coord, SLOT_WEIGHT)], 0u));
    if weight > 1.0 {
        gene_field = mix(gene_field, gene_sum / weight, GENE_BLEND);
    }

    // Cap well above the display range: the material tone-maps this itself, and
    // letting hot spots run to 8 gives the bloom something to catch.
    textureStore(
        trail_write,
        coord,
        vec4<f32>(min(value, vec3<f32>(8.0)), clamp(gene_field, 0.0, 1.0)),
    );
}

// Seeds the trail. Run once when the visual starts.
@compute @workgroup_size(8, 8)
fn clear(@builtin(global_invocation_id) gid: vec3<u32>) {
    let coord = vec2<i32>(gid.xy);
    if !in_bounds(coord) {
        return;
    }
    // A faint noise floor rather than zero. On a perfectly flat trail every
    // sensor reads the same value and the agents' tie-break is the only thing
    // driving them, which takes far longer to organise. Each species gets its
    // *own* noise, which is what gives the cycle somewhere to start: three
    // identical fields would stay symmetric and no front would ever form.
    let p = vec2<f32>(coord);
    let a = hash12(p * 0.010 + params.time) * 0.05;
    let b = hash12(p * 0.013 + params.time + 37.0) * 0.05;
    let c = hash12(p * 0.017 + params.time + 91.0) * 0.05;
    // The trait field starts as coarse noise rather than flat, so the first
    // domains have something to grow from. Much lower frequency than the trail
    // noise: these are meant to be regions, not speckle.
    let gene = hash12(floor(p * 0.02) + params.time * 0.1);
    textureStore(trail_write, coord, vec4<f32>(a, b, c, gene));

    for (var slot = 0u; slot < SLOTS_PER_TEXEL; slot++) {
        atomicStore(&deposits[deposit_index(coord, slot)], 0u);
    }
}
